### ISSUE TITLE
Allow users to submit a website link

### ISSUE THREAD

**Issue by VeerpalBrar** [itsninaricci29/CONNECTeD#82]
- Allow users to submit a link to their personal website when they sign up and have it be saved in the database
- Have the website appear as a link on the profile page
- allow user to update the website link on the edit profile page and have it be updated in the database
- We will need to add a website_link column to the users table. This can be done using sequelize migrations. 

Implemenation details: 
Instead of deleting and creating your database from scratch you can modify you database using a migration. 

1. First, in server/src do `npm install` to make sure sequelize-cli is installed
2. Then do `npx sequelize-cli migration:generate --name add-website-link` . This will create a new migration file inside `server/src/migrations`
3. A migration file just specifies how the database table needs to change ie are you adding a column, deleting the column, etc. Update the new migration file to specify the creation of a new profile column in the Use table. Here is a template you can follow. This adds the picture column to Project table. 
```
module.exports = {
  up: (queryInterface, Sequelize) => {      --> up method is more making the change
    return queryInterface.addColumn('Projects', 'picture', {
          type: Sequelize.DataTypes.STRING,
        })
  },

  down: (queryInterface, Sequelize) => {   --> down method is for undoing the change
    return queryInterface.removeColumn('Projects', 'picture')
  }
};
```
4. Update the model/User.js class to also include this new profile column.  
5. run `npx sequelize-cli db:migrate` to actually modify the database.

**Comment by itsninaricci29** [comment]
The link option is already present in the NewUserForm.vue

**Comment by VeerpalBrar** [comment]
The option is present but we don't save it in the backend yet. I'll update the issue to clarify this point.
