### ISSUE TITLE
If user does not exist redirect to page not found

### ISSUE THREAD

**Issue by VeerpalBrar** [itsninaricci29/CONNECTeD#86]
If you visit a page for a user id that is not in the database, the page loads with null values. Let's redirect the user to a page not found link instead.

**Implementation Details**
- In the redirect controller create a route for "/connect/profile/:id" that match all dynamic profile routes
````    
app.get('/user/:id', function(req,res){  // matches /user/1 or /user/2 etc
   var user = req.params.id;   // this allows you to get the value of id
});
````
- use `req.param.id` to get the user id and query the db to see if user exists. If the user exists, send them to their profile. 
- if the user does not exist, send them to a page not found route ('/connect/404').

**Comment by itsninaricci29** [comment]
I've created the 404 page not found! 
/component/404.vue
